Quote.destroy_all
Quote.create(source:"Fyodor Dostoyevsky",philosophy:"Existentialism",quote:"The soul is healed by being with children.",_id:"2HxACEhfZ8DkuNnZ")
Quote.create(source:"Rumi",philosophy:"Mysticism",quote:"Don't be satisfied with stories, how things have gone with others. Unfold your own myth.",_id:"2Wqp3NV8XvZs2HKY")
Quote.create(source:"Carl G. Jung",philosophy:"Mysticism",quote:"In all chaos there is a cosmos, in all disorder a secret order.",_id:"3YIXXzhZvIUh7yPn")
Quote.create(source:"Jean-Paul Sartre",philosophy:"Existentialism",quote:"There may be more beautiful times, but this one is ours.",_id:"6m6bFLLUSCZGPNyM")
Quote.create(source:"Friedrich Nietzsche",philosophy:"Existentialism",quote:"Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",_id:"By6UZc59LIsxuYY3")
Quote.create(source:"Jean-Paul Sartre",philosophy:"Existentialism",quote:"Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. It is up to you to give [life] a meaning.",_id:"CyxlEzgRhuzOCjtI")
Quote.create(source:"Friedrich Nietzsche",philosophy:"Existentialism",quote:"The individual has always had to struggle to keep from being overwhelmed by the tribe. If you try it, you will be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.",_id:"JDHY2ehQXA8oQhBU")
Quote.create(source:"Rumi",philosophy:"Mysticism",quote:"Dance, when you're broken open. Dance, if you've torn the bandage off. Dance in the middle of the fighting. Dance in your blood. Dance when you're perfectly free.",_id:"JL7XIQSS5t3ibxRG")
Quote.create(source:"Fyodor Dostoyevsky",philosophy:"Existentialism",quote:"But how could you live and have no story to tell?",_id:"Kg9wd2v25o0TbWE6")
Quote.create(source:"Epictetus",philosophy:"Stoicism",quote:"First say to yourself what you would be; and then do what you have to do.",_id:"P4U3wiseSlTsQtQ5")
Quote.create(source:"Jean-Paul Sartre",philosophy:"Existentialism",quote:"Life begins on the other side of despair.","_id":"QoFvXpd4E3JwsQLA")
Quote.create(source:"Jean-Paul Sartre",philosophy:"Existentialism",quote:"If you're lonely when you're alone, you're in bad company.",_id:"QxShUpA8tlegqZ4P")
Quote.create(source:"Alan Watts",philosophy:"Mysticism",quote:"You are an aperture through which the universe is looking at and exploring itself.",_id:"RCcTXwS9eTJctXtD")
Quote.create(source:"Marcus Aurelius",philosophy:"Stoicism",quote:"Waste no more time arguing what a good man should be. Be One.",_id:"SfYqA7dCjxytVaHb")
Quote.create(source:"Rumi",philosophy:"Mysticism",quote:"If you are irritated by every rub, how will your mirror be polished?",_id:"Si8XIQY57qqvbdrs")
Quote.create(source:"Alan Watts",philosophy:"Mysticism",quote:"Man suffers only because he takes seriously what the gods made for fun.",_id:"U77NASaj0fAXrOYO")
Quote.create(source:"Seneca",philosophy:"Stoicism",quote:"Luck is what happens when preparation meets opportunity.",_id:"UBBWlyiKFHp9bJt4")
Quote.create(source:"Friedrich Nietzsche",philosophy:"Existentialism",quote:"And those who were seen dancing were thought to be insane by those who could not hear the music.",_id:"UnbrihZI9cgQo1BU")
Quote.create(source:"Seneca",philosophy:"Stoicism",quote:"Sometimes even to live is an act of courage.",_id:"VoHnlEdkOMooqECd")
Quote.create(source:"Jean-Paul Sartre",philosophy:"Existentialism",quote:"Better to die on one's feet than to live on one's knees.",_id:"XI8BBGHsKUUnO4iR")
Quote.create(source:"Marcus Aurelius",philosophy:"Stoicism",quote:"The best revenge is not to be like your enemy.",_id:"XzDMqQbdWLM3iLVF")
Quote.create(source:"Epictetus",philosophy:"Stoicism",quote:"No man is free who is not master of himself.",_id:"Y0F7KBTBlGZma7sp")
Quote.create(source:"Carl G. Jung",philosophy:"Mysticism",quote:"Show me a sane man and I will cure him for you.",_id:"buG0dcFCEKVIzdWy")
Quote.create(source:"Epictetus",philosophy:"Stoicism",quote:"Don't explain your philosophy. Embody it.",_id:"caC1oWy1CQyd5Ebb")
Quote.create(source:"Fyodor Dostoyevsky",philosophy:"Existentialism",quote:"I say let the world go to hell, but I should always have my tea.",_id:"fbYKDOJ4uFfv97tp")
Quote.create(source:"Carl G. Jung",philosophy:"Mysticism",quote:"One does not become enlightened by imagining figures of light, but by making the darkness conscious.",_id:"h5HttNOoWKK263GN")
Quote.create(source:"Marcus Aurelius",philosophy:"Stoicism",quote:"The soul becomes dyed with the colour of its thoughts.",_id:"hFQU7o0aGcxlIAbd")
Quote.create(source:"Fyodor Dostoyevsky",philosophy:"Existentialism",quote:"The darker the night, the brighter the stars. The deeper the grief, the closer is God!",_id:"jLcTNB56Pwf7WT00")
Quote.create(source:"Seneca",philosophy:"Stoicism",quote:"A wise man is content with his lot, whatever it may be, without wishing for what he has not.",_id:"kBqBzdHsJrY9ecxm")
Quote.create(source:"Epictetus",philosophy:"Stoicism",quote:"First learn the meaning of what you say, and then speak.",_id:"mdDw5PT26q95BOjF")
Quote.create(source:"Carl G. Jung",philosophy:"Mysticism",quote:"Until you make the unconscious conscious, it will direct your life and you will call it fate.",_id:"o60A8gzQva0rsty8")
Quote.create(source:"Marcus Aurelius",philosophy:"Stoicism",quote:"If it is not right, do not do it, if it is not true, do not say it.",_id:"onOHW37bBtcHa7AM")
Quote.create(source:"Marcus Aurelius",philosophy:"Stoicism",quote:"Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",_id:"oniQPv9VZuLtuY9D")
Quote.create(source:"Rumi",philosophy:"Mysticism",quote:"The wound is the place where the Light enters you.",_id:"ooufDhwTwkiXy6B9")
Quote.create(source:"Alan Watts",philosophy:"Mysticism",quote:"Muddy water is best cleared by leaving it alone.",_id:"pbRRkhz1IeC0JKSB")
Quote.create(source:"Friedrich Nietzsche",philosophy:"Existentialism",quote:"He who has a why to live for can bear almost any how.",_id:"q9T2pPdhwxOTTleI")
Quote.create(source:"Fyodor Dostoyevsky",philosophy:"Existentialism",quote:"The mystery of human existence lies not in just staying alive, but in finding something to live for.",_id:"sObKkljnyMqddzGJ")
Quote.create(source:"Epictetus",philosophy:"Stoicism",quote:"It's not what happens to you, but how you react to it that matters.",_id:"ucHJcQ9vZ51ES5go")
Quote.create(source:"Seneca",philosophy:"Stoicism",quote:"Difficulties strengthen the mind, as labor does the body.",_id:"ukQqHm7mU3N88t8c")
Quote.create(source:"Carl G. Jung",philosophy:"Mysticism",quote:"Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.",_id:"vPUombjJLM4QylD7")
Quote.create(source:"Rumi",philosophy:"Mysticism",quote:"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",_id:"vYbq2GFcaZh7LnUU")
Quote.create(source:"Seneca",philosophy:"Stoicism",quote:"It is the power of the mind to be unconquerable.",_id:"vYo23ovrf6rlXqMT")
Quote.create(source:"Alan Watts",philosophy:"Mysticism",quote:"Trying to define yourself is like trying to bite your own teeth.",_id:"vxoBOkPRuGbUdPWi")
Quote.create(source:"Friedrich Nietzsche",philosophy:"Existentialism",quote:"That which does not kill us makes us stronger.",_id:"zHG0sL7d1vnGr8ry")
Quote.create(source: "Oscar Wilde", philosophy: "satiricism", quote: "Always forgive your enemies; nothing annoys them so much.",_id:"vHJkfDHkIldSsjEru")
Quote.create(source: "Oscar Wilde", philosophy: "satiricism", quote: "Be yourself; everyone else is already taken.",_id:"vHJkHDHkIhdSsjgru")
Quote.create(source: "Oscar Wilde", philosophy: "satiricism", quote: "The public is wonderfully tolerant. It forgives everything except genius.",_id:"vHJkKDHkIhdSOjgru")
Quote.create(source: "Oscar Wilde", philosophy: "satiricism", quote: "Some cause happiness wherever they go; others whenever they go.",_id:"vHJkkDHkIPdSsjgru")  
Quote.create(source: "Oscar Wilde", philosophy: "satiricism", quote: "Women are meant to be loved, not to be understood.",_id:"vHJkhDHkIndSEjgru")  
                                                             